#!/bin/sh

indent() {
  sed -u 's/^/       /'
}

echo "-----> Install ffmpeg"

cd $BUILD_DIR

echo "Installing build dependencies" | indent
echo deb http://archive.ubuntu.com/ubuntu precise universe multiverse >> /etc/apt/sources.list;
apt-get update;
apt-get -y install autoconf automake build-essential git mercurial cmake libass-dev libgpac-dev libtheora-dev libtool libvdpau-dev libvorbis-dev pkg-config texi2html zlib1g-dev libmp3lame-dev wget yasm openssl libssl-dev;
apt-get clean

mkdir -p $CACHE_DIR
cd $CACHE_DIR

echo "Fetching Sources" |indent

echo "Fetching l-smash" | indent
git clone --depth 1 https://github.com/l-smash/l-smash
echo "Fetching x264" | indent
git clone --depth 1 git://git.videolan.org/x264.git
echo "Fetching x265" | indent
hg clone https://bitbucket.org/multicoreware/x265
echo "Fetching fdk-aac" | indent
git clone --depth 1 git://github.com/mstorsjo/fdk-aac.git
echo "Fetching libvpx" | indent
git clone --depth 1 https://chromium.googlesource.com/webm/libvpx
echo "Fetching ffmpeg" | indent
git clone --depth 1 git://source.ffmpeg.org/ffmpeg
echo "Fetching opus" | indent
git clone https://git.xiph.org/opus.git
echo "Fetching aacgain" | indent
git clone --depth 1 https://github.com/mulx/aacgain.git

echo "Build L-SMASH" | indent

cd $CACHE_DIR/l-smash
./configure
make -j $(nproc)
make install

echo "Build libx264" | indent

cd $CACHE_DIR/x264
./configure --enable-static
make -j 8
make install

echo "Build libx265" | indent

cd $CACHE_DIR/x265/build/linux
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ../../source
make -j 8
make install

echo "Build libfdk-aac" | indent

cd $CACHE_DIR/fdk-aac
autoreconf -fiv
./configure --disable-shared
make -j 8
make install

echo "Build libvpx" | indent

cd $CACHE_DIR/libvpx
./configure --disable-examples
make -j 8
make install

echo "Build libopus" | indent

cd $CACHE_DIR/opus
./autogen.sh
./configure --disable-shared
make -j 8
make install

echo "Build ffmpeg." | indent

cd $CACHE_DIR/ffmpeg
./configure --extra-libs="-ldl" --enable-gpl --enable-libass --enable-libogg --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-openssl
make -j 8
make install

echo "Build aacgain" | indent

cd $CACHE_DIR/aacgain/mp4v2
./configure && make -k -j 8 # some commands fail but build succeeds
cd $CACHE_DIR/aacgain/faad2
./configure && make -k -j 8 # some commands fail but build succeeds
cd $CACHE_DIR/aacgain
./configure && make -j 8 && make install


